import type { Metadata } from "next";
import { Sora, Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/layout/Header";
import {Footer} from "@/components/layout/Footer";

const sora = Sora({
    variable: "--font-heading",
    subsets: ["latin"],
});

const zenKaku = Zen_Kaku_Gothic_New({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: ["300", "400", "500", "700"]
});

export const metadata: Metadata = {
    title: "imflawlezz.dev",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${sora.variable} ${zenKaku.variable} antialiased mt-17 md:mt-18`}>
            <Header/>
                {children}
            <Footer/>
        </body>
        </html>
    );
}
